#pragma once

#define VULKAN_HPP_NO_STRUCT_CONSTRUCTORS // for designated initialization w/ vulkan
#define GLFW_INCLUDE_VULKAN        // REQUIRED only for GLFW CreateWindowSurface. you could ditch the header right below this in exchange for this #define.

#if defined(__INTELLISENSE__) || !defined(USE_CPP20_MODULES)
#include <vulkan/vulkan_raii.hpp> // https://github.com/KhronosGroup/Vulkan-Headers/blob/main/include/vulkan/vulkan.hpp
#else
import vulkan_hpp;
#endif

// The perspective projection matrix generated by GLM will use the OpenGL depth range of [-1.0 to 1.0] by default.
// Vulkan uses the range of [0.0 to 1.0], hence:
#define GLM_FORCE_DEPTH_ZERO_TO_ONE

// 3rd party libs
#include <GLFW/glfw3.h>
#include <vulkan/vulkan.h> // https://github.com/KhronosGroup/Vulkan-Headers/blob/main/include/vulkan/vulkan.h (gateway to a bunch of other garbage)
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>

#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>

#define TINYOBJLOADER_IMPLEMENTATION
#include <tiny_obj_loader.h>

// window stuff
#define GLFW_EXPOSE_NATIVE_WIN32    // Required to define for the #include below -- allows GLFW to show Windows handles (HWND/hInstance access)
#include <GLFW/glfw3native.h>       // Gives GLFW Native interface for this OS (so allows Win32 Functions on GLFW windows)
#define VK_USE_PLATFORM_WIN32_KHR // Similarily with GLFW, this specifies to Vulkan that you want to get Vulkan's WindowsOS-specific functions (VkWin32SurfaceCreateInfoKHR/vkCreateWin32SurfaceKHR - access to these functions from Vulkan)

// std
#include <algorithm>
#include <cstdlib>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <fstream>
#include <chrono>

// my utils
#include "random_utils.cpp"